name: Generate Snake Animation

on:
  push:
  workflow_dispatch:
  schedule: 
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate the snake animation
        uses: Platane/snk@v2
        with:
          github_user_name: Navist
          outputs: dist/github-contribution-grid-snake.svg

      - name: Upload the generated snake
        uses: actions/upload-artifact@v3
        with:
          name: snake-animation
          path: dist

      - name: Push the SVG to GitHub
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: ./dist
