name: Generate Snake Animation

on:
  push:  # Runs on pushes to the repository
  workflow_dispatch:  # Allows manual runs
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight UTC

jobs:
  build:
    runs-on: ubuntu-latest  # Specifies the environment for the job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Checks out your repository code

      - name: Generate the snake animation  # Generates the snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: Navist  # Replace with your GitHub username
          outputs: dist/github-contribution-grid-snake.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Ensures API access

      - name: Upload the snake animation
        uses: actions/upload-artifact@v3
        with:
          name: snake-animation
          path: dist

      - name: Deploy to GitHub Pages  # Deploys to the output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: ./dist
